// <auto-generated />
using HillCavernFair.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HillCavernFair.Data.Migrations
{
    [DbContext(typeof(HillCavernFairContext))]
    [Migration("20230709150906_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("HillCavernFair.Domain.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paragraph");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "How did you get here? Your memory is fuzzy and ill-formed, and it makes you sick to your stomach every time you try to focus on it. You’re standing beside your car, in an empty gravel-covered parking lot surrounded by woods. Green encroaches on all sides, vines and grass and burrs reaching past the barriers around the parking lot and towards you and your car. ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Before you an is an archway topped by a rusted and faded metal sign bearing the words ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 3,
                            Content = "HILL CAVERN FAIR",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 4,
                            Content = "The vines don’t touch this archway, rickety and ill-maintained as it is. ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 5,
                            Content = "You have a choice to make, here. ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Both choices make you feel bad, but different kinds of bad. ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 7,
                            Content = "The idea of going forward into this place fills you with dread: the dread of looking over edge of a very tall cliff and considering the bottom, the dread of having to admit to your boss that you’ve made an error that you know isn’t correctable, the dread of many, many potential bad futures and a handful of good ones. ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 8,
                            Content = "On the other hand, getting in your car and driving away feels like loss. The loss of your favorite toy in a park where you will never return. The loss of your childhood neighborhood when you moved and had to make all new friends and an all new identity in an all new place– never ever quite feeling like you fit in the same way you did in your old home. An important loss, but something that will fade with time. A loss that will hit you years later in ways you can’t put into words. ",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Type “dread” to continue into Hill Cavern Fair, type “loss” to get back into your car and try to find your way back home.",
                            StoryId = "Intro"
                        },
                        new
                        {
                            Id = 10,
                            Content = "You step forward under the sign and Hill Cavern Fair opens up to you amidst the woods. You first notice the darkness of the park–you’ve never seen a theme park so shaded by trees and hills. You would expect from the name that you would be on a hill, or maybe there would be a cave nearby? but you see no indication of either. ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 11,
                            Content = "In fact, the park seems surrounded by hills, set in the lowest places among them. The path is now paved, but it was paved long ago, and is beset with potholes and weeds. A small turnstile blocks your way, and this is surely where your exploration will be stopped, because there is no way this place is open. Your car was the only one in the parking lot, and nothing here seems maintained. ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 12,
                            Content = "“It’s free today,” a cracked, aged voice says, from your left, while you were looking right. ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 13,
                            Content = "You jump and turn. A man stands beside you, in a faded polo shirt. He is unbelievably old, bent by the weight of years and overwhelmingly the color of yellowed receipts, from his tar-stained teeth to his liver-spotted skin. A name tag on his chest says /“Eugene./” ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 14,
                            Content = "You don’t have a chance to ask for more information as he thrusts a ticket and a park map in your hand and gestures to the turnstile. “Free on Tuesdays.” ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Is it Tuesday? You don't think so. ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 16,
                            Content = "The turnstile creaks loudly as you enter Hill Cavern Fair. ",
                            StoryId = "ChoiceDread"
                        },
                        new
                        {
                            Id = 17,
                            Content = "You climb into your car and turn your back on the sign, driving down the gravel path that you surely followed into this place. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Surely you did. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 19,
                            Content = "And surely, as you drive down this winding gravel road through tightly packed trees with branches that slap your windshield and animals that you perceive only as darting, furtive movement, you will eventually reach a main road. A paved, smooth, road. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Surely you will. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 21,
                            Content = "Surely, right around this corner. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Well, maybe the next turn. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 23,
                            Content = "Up over this hill. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Eventually you’ll be home, wherever that is, or was. ",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Surely.",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 26,
                            Content = "END",
                            StoryId = "ChoiceLoss"
                        },
                        new
                        {
                            Id = 27,
                            Content = "You head down the cracked asphalt path in the direction the map promises a snack stand. You’re unsure if a place like this is somewhere you would like to actually eat food, but curiosity leads you on to the little booth tucked into a mass of trees and vines that seem only days from swallowing the building entirely. The vines are so thick along the cracked and aged wood that you wonder how an employee could get inside the building. Flecks of paint hint that at one time this shack was brightly colored, but now exposed gray wood and rusted nails are its defining features.",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 28,
                            Content = "You’re sure this place is completely closed until you catch sight of the extremely improbable man behind the counter. ",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 29,
                            Content = "An old man with skin the color of yellowed receipts is hunched over an equally ancient cash register. His name tag reads “Gene.” To his left, a hand painted, chipped sign advertises the wares of the Snack Stand.",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 30,
                            Content = "SLUSHEE — 30¢",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 31,
                            Content = "CARAMEL CORN — 25¢",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 32,
                            Content = "COTTON CANDY — 15¢",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Before you can ask if the prices are a joke, the man says, “The slushees are new. Added ‘em only a little while ago. They’re cherry flavored.” He puffs himself up, standing at his full height, which is still shorter than you. ",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 34,
                            Content = "What'll it be?",
                            StoryId = "SnackStandMain"
                        },
                        new
                        {
                            Id = 35,
                            Content = "The slushee machine does not, in fact, look new. It looks as old and dusty as the rest of the place, and you question if it’s ever been cleaned in the however-many-years it’s been here. The frozen drink swirling inside is red, but the rim of the drink spout looks like it has some sort of black film on it–mold, or mildew.",
                            StoryId = "SnackStandSlushee"
                        },
                        new
                        {
                            Id = 36,
                            Content = "Do you want to order a slushee?",
                            StoryId = "SnackStandSlushee"
                        },
                        new
                        {
                            Id = 37,
                            Content = "It really was only 30 cents, but you have a feeling if you drank more than your initial sip your medical bills would be much more expensive. It tastes exactly like wet laundry forgotten in a washing machine smells. You throw the cup away as soon as you leave the snack stand.",
                            StoryId = "SnackStandSlusheeYes"
                        },
                        new
                        {
                            Id = 38,
                            Content = "A good choice, really.",
                            StoryId = "SnackStandSlusheeNo"
                        },
                        new
                        {
                            Id = 39,
                            Content = "There are popcorn boxes behind the man that you assume are filled with caramel corn. They look dusty–are those spiderwebs? Even so, you feel a draw to the caramel corn. It feels like something worthwhile to have.",
                            StoryId = "SnackStandCaramelCorn"
                        },
                        new
                        {
                            Id = 40,
                            Content = "Do you want to order caramel corn?",
                            StoryId = "SnackStandCaramelCorn"
                        },
                        new
                        {
                            Id = 41,
                            Content = "It really only cost 25 cents. The box is dusty and cobwebby, but the caramel corn inside smells good, and when you eat some it’s satisfying, with a sweet crunch. You carry the box with you throughout the rest of the park.",
                            StoryId = "SnackStandCaramelCornYes"
                        },
                        new
                        {
                            Id = 42,
                            Content = "Bags of cotton candy hang off the ceiling of the snack stand. They look perfectly normal, and even relatively fresh, despite there being no cotton candy machine in sight.",
                            StoryId = "SnackStandCottonCandy"
                        },
                        new
                        {
                            Id = 43,
                            Content = "Do you want to order cotton candy?",
                            StoryId = "SnackStandCottonCandy"
                        },
                        new
                        {
                            Id = 44,
                            Content = "For 15 cents you get a pretty big bag of pink cotton candy. It tastes just like all the other cotton candy you’ve ever tasted–sweet and light.",
                            StoryId = "SnackStandCottonCandyYes"
                        },
                        new
                        {
                            Id = 45,
                            Content = "As you walk away from the snack stand, picking bits of cotton candy off the cloud and letting it dissolve in your mouth, you’re struck by how crowded the place is. Maybe you just came right as they opened and beat the initial crowds– because now there are people on all sides of you. It’s really quite bustling. Mostly families, kids running by in excitement towards this or that attraction, adults laughing and calling for them to wait up– you blink as the sun hits you right in your eyes and–",
                            StoryId = "SnackStandCottonCandyYes"
                        },
                        new
                        {
                            Id = 46,
                            Content = "Silence. Empty asphalt. Shadows from the hills, and clouds overhead.",
                            StoryId = "SnackStandCottonCandyYes"
                        },
                        new
                        {
                            Id = 47,
                            Content = "No, you were mistaken. Hill Cavern Fair is as empty and forlorn as when you first stepped inside. In fact, you’re sure it’s only you and Gene here.",
                            StoryId = "SnackStandCottonCandyYes"
                        },
                        new
                        {
                            Id = 48,
                            Content = "The Grand Stage appears to be neither grand, nor a stage.",
                            StoryId = "GrandStageMain"
                        },
                        new
                        {
                            Id = 49,
                            Content = "What you find in the place marked on the map is a small outdoor amphitheater of the kind often found in small parks: three levels of concrete seating set into a hill with a flat paved area in the center that it would be rather generous to term a “stage”. The woods are encroaching more into this area than any of the others: there are vine-choked trees on all sides of the paved area, and cracks in the concrete as it continues to lose the fight against the roots of those trees. The vines hang down into the space, and various plants are sprouting from the cracks. Piles of years of leaves and other rotting plant matter line the edges of the concrete.",
                            StoryId = "GrandStageMain"
                        },
                        new
                        {
                            Id = 50,
                            Content = "This seems more to be a small rest area than an attraction, but sure enough there is a sign amid the weeds on the stage that seems to indicate a performance will occur here in five minutes.",
                            StoryId = "GrandStageMain"
                        },
                        new
                        {
                            Id = 51,
                            Content = "Will you stay for the performance?",
                            StoryId = "GrandStageMain"
                        },
                        new
                        {
                            Id = 52,
                            Content = "You wait for much longer than five minutes, but the wait is restorative and so you don’t leave when the time drags on. You find yourself relaxing back against the concrete, following the journeys of the cracks across it with your eyes.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 53,
                            Content = "You only look up when you hear a throat being cleared.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 54,
                            Content = "An old, old man with a polo shirt so faded and soiled it’s the color of yellowed receipts stands before you. On his chest is a name tag that reads “Gene.”",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 55,
                            Content = "He stands on the stage with all the dignity and air of a storied actor. He begins his story in a booming, authoritative voice that allows no interruption.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 56,
                            Content = "“In 1947, Brothers Raymond and Eugene Hill bought a large parcel of land just ten miles from the newly established Mammoth Cave National Park. They believed the land to be untouched woodland, ripe for development into a variety of attractions that would surely yield unimaginable profit as the tourists poured into Kentucky for their visits to what would eventually be known as the world’s longest cave system.” He lets this statement hang in the air for a few moments, presumably for you to absorb the grandeur of the region you find yourself in.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 57,
                            Content = "“Shortly after the brothers Hill opened Hill Cavern Fair, they realized their mistake, for in the long, uncharted caverns beneath our feet hide secrets. For millennia the fragile limestone lining empty pockets in the earth has given way beneath the feet of both animal and man. Those who avoid the sinkholes aren’t safe– the Underneath claims bodies by enchanting explorers with its caverns and by courting powerful men with its coal.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 58,
                            Content = "“Here, where the caverns yawn wide, where the bodies accumulate, something was stirred. Something hungry and old and greedy crawled from its gore-filled hole and took a form it thought was less threatening to its prey and settled in the heart of Hill Cavern Fair, a spider waiting upon its web.”",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 59,
                            Content = "Gene goes silent after this last declaration, staring at a spot behind you.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 60,
                            Content = "After a few minutes of silence, it seems like a good idea for you to leave.",
                            StoryId = "GrandStageYes"
                        },
                        new
                        {
                            Id = 61,
                            Content = "Nothing that happens in this place could be good. You turn away and head back to the main path.",
                            StoryId = "GrandStageNo"
                        },
                        new
                        {
                            Id = 62,
                            Content = "The petting zoo seemed like a safe choice, but as you approach it now you’re filled with the same dread you felt making the decision to come inside Hill Cavern Fair. The Petting Zoo has no attendant, and no animals in sight. A cheery hand painted sign hangs lopsided by one nail over the entrance.",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 63,
                            Content = "HILL CAVERN PETTING ZOO",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 64,
                            Content = "The entire area is surrounded by a wooden fence, and the surrounding forest, despite its enthusiasm for the other buildings in this park, does not encroach beyond it. The ground is dry and dusty, with none of the animal droppings found at similar petting zoos across the world.",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 65,
                            Content = "On the far side of the animal enclosure is a small building– you assume a shelter for the animals– in surprisingly pristine condition. It looks like it has recently been painted, or maybe even recently built. It’s solid white and has a similarly hand painted sign.",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 66,
                            Content = "PLEASE— DON’T FEED THE ANIMALS!",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 67,
                            Content = "THANK YOU, MGMT",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 68,
                            Content = "There are of course no animals in sight, only an empty enclosure with a foreboding air that twists your stomach. Something is very, very wrong here, more wrong than the cumulative wrongness of the rest of Hill Cavern Fair.",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 69,
                            Content = "Will you explore further?",
                            StoryId = "PettingZooMain"
                        },
                        new
                        {
                            Id = 70,
                            Content = "You step through the wooden gate onto the hard packed dirt. You kick up dust as you walk towards the bright white enclosure. When you touch the door to step inside, it is skin-warm, like the enclosure itself has blood pumping just beneath the fresh coats of paint.",
                            StoryId = "PettingZooYesHasCC"
                        },
                        new
                        {
                            Id = 71,
                            Content = "Inside is filled with sweet-smelling clean hay. A single animal is curled up atop the hay, a small brown fawn with bright white spots. You’ve woken it up. It lifts its head to gaze at you and bleats a greeting—or is it a question?",
                            StoryId = "PettingZooYesHasCC"
                        },
                        new
                        {
                            Id = 72,
                            Content = "Yes, it’s a question.",
                            StoryId = "PettingZooyesHasCC"
                        },
                        new
                        {
                            Id = 73,
                            Content = "You fall to your knees as the words of a god fill your brain.",
                            StoryId = "PettingZooYesHasCC"
                        },
                        new
                        {
                            Id = 74,
                            Content = "HAVE YOU AN OFFERING, OR HAVE YOU DISTURBED MY SLUMBER WITHOUT REASON?",
                            StoryId = "PettingZooYesHasCC"
                        },
                        new
                        {
                            Id = 75,
                            Content = "An offering? All you have on you is the caramel corn! Will that be enough?",
                            StoryId = "PettingZooYesHasCC"
                        },
                        new
                        {
                            Id = 76,
                            Content = "Will you offer the Deer God your caramel corn?",
                            StoryId = "PettingZooYesHasCC"
                        },
                        new
                        {
                            Id = 77,
                            Content = "With trembling hands, you pull the small, dusty box of caramel corn from your pocket and hold it out to the little fawn.",
                            StoryId = "PettingZooYesHasCCYes"
                        },
                        new
                        {
                            Id = 78,
                            Content = "The fawn stands in a slow unfurling that reminds you more of a spider than any mammal you’ve seen. It has too many legs, and those legs are too long, with too many joints. It flicks its ears, and you fully collapse on the ground before it.",
                            StoryId = "PettingZooYesHasCCYes"
                        },
                        new
                        {
                            Id = 79,
                            Content = "You hear the gentle rustling of hay as the fawn approaches your prone form.",
                            StoryId = "PettingZooYesHasCCYes"
                        },
                        new
                        {
                            Id = 80,
                            Content = "A soft crunch near your ear as it eats some of the spilled caramel corn. More rustling, and you realize it’s gently snuffling the inside of the box as it eats more.",
                            StoryId = "PettingZooYesHasCCYes"
                        },
                        new
                        {
                            Id = 81,
                            Content = "You wake up outside the enclosure. In your pocket is a green rock with an image of an eight-legged stag engraved upon it, and your caramel corn is gone.",
                            StoryId = "PettingZooYesHasCCYes"
                        },
                        new
                        {
                            Id = 82,
                            Content = "Surely the caramel corn wouldn’t be enough. Besides, the sign said not to feed the animals!",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 83,
                            Content = "You have nothing to offer the little fawn, and so you shake your head.",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 84,
                            Content = "The fawn stands in a slow unfurling that reminds you more of a spider than any mammal you’ve seen. It has too many legs, and those legs are too long, with too many joints. It flicks its ears, and you fully collapse on the ground before it.",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 85,
                            Content = "You hear the gentle rustling of hay as the fawn approaches your prone form.",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 86,
                            Content = "You hear the crunch seconds before your body allows you to feel the white hot pain, shooting up your arm and filling your entire body.",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 87,
                            Content = "It’s a small blessing that you cannot see the gore of what the fawn is doing to your body, and a far larger blessing that everything goes black before it is finished.",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 88,
                            Content = "END",
                            StoryId = "PettingZooYesHasCCNo"
                        },
                        new
                        {
                            Id = 89,
                            Content = "You step through the wooden gate onto the hard packed dirt. You kick up dust as you walk towards the bright white enclosure. When you touch the door to step inside, it is skin-warm, like the enclosure itself has blood pumping just beneath the fresh coats of paint.",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 90,
                            Content = "Inside is filled with sweet-smelling clean hay. A single animal is curled up atop the hay, a small brown fawn with bright white spots. You’ve woken it up. It lifts its head to gaze at you and bleats a greeting—or is it a question? ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 91,
                            Content = "Yes, it's a question.",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 92,
                            Content = "You fall to your knees as the words of a god fill your brain.",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 93,
                            Content = "HAVE YOU AN OFFERING, OR HAVE YOU DISTURBED MY SLUMBER WITHOUT REASON?",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 94,
                            Content = "An offering? Do you have anything on you that you can offer the fawn? You search your pockets frantically.",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 95,
                            Content = "All you have is the park map and your ticket. These aren’t going to be enough. ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 96,
                            Content = "You have nothing to offer the little fawn, and so you shake your head. ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 97,
                            Content = "The fawn stands in a slow unfurling that reminds you more of a spider than any mammal you’ve seen. It has too many legs, and those legs are too long, with too many joints. It flicks its ears, and you fully collapse on the ground before it. ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 98,
                            Content = "You hear the gentle rustling of hay as the fawn approaches your prone form. ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 99,
                            Content = "You hear the crunch seconds before your body allows you to feel the white hot pain, shooting up your arm and filling your entire body. ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 100,
                            Content = "It’s a small blessing that you cannot see the gore of what the fawn is doing to your body, and a far larger blessing that everything goes black before it is finished. ",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 101,
                            Content = "END",
                            StoryId = "PettingZooYesNoCC"
                        },
                        new
                        {
                            Id = 102,
                            Content = "You’ve made a good decision for now, though something tells you that you should return with something worthwhile.",
                            StoryId = "PettingZooNo"
                        },
                        new
                        {
                            Id = 103,
                            Content = "You’re not sure how anything in this place could be more haunted than the park itself, but you head off for the “Haunted House” marked on the map.",
                            StoryId = "HauntedHouseMain"
                        },
                        new
                        {
                            Id = 104,
                            Content = "What you find isn’t really a house–it’s a large metal box that looks like it could be easily folded up and hauled off by a truck to a carnival in the next state–or at least it once could have been. Rust and years and the woods have seeped into its cracks, and if someone attempted to fold it up and cart it away it wouldn’t survive the first pothole it encountered on its way out of the park. ",
                            StoryId = "HauntedHouseMain"
                        },
                        new
                        {
                            Id = 105,
                            Content = "The metal structure is gaudily painted with faux stonework, cartoon skeletons peeking from around corners and through barred windows. The fading of years hasn’t diminished this old ride’s charm, and it’s a surprisingly welcome sight, a carnival staple planted amongst these claustrophobic hills. ",
                            StoryId = "HauntedHouseMain"
                        },
                        new
                        {
                            Id = 106,
                            Content = "And, right at the entrance, an old, old man with hair the color of yellowed receipts waves cheerfully at you. “Step right up, step right up! Have the fright of your life!” His face is so wrinkled it looks like melted wax, and on his polo shirt is a name tag that reads “Gene.” He really seems quite nice, and enthusiastic to get you on this old ride. ",
                            StoryId = "HauntedHouseMain"
                        },
                        new
                        {
                            Id = 107,
                            Content = "Will you ride the Haunted House?",
                            StoryId = "HauntedHouseMain"
                        },
                        new
                        {
                            Id = 108,
                            Content = "You climb the metal steps up to the entrance of the ride. From here, you can see there is actually a cart on a track leading towards a door painted to look as though it’s wood. There’s even a safety bar on the cart, implying the ride might reach speeds for which a safety bar is required. You climb into the cart and Gene cheerfully checks the safety bar before stepping back to a control panel and starting the ride. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 109,
                            Content = "Mechanical whirs and clinks and roars sound as your cart is pulled forward. The metal door swings open at the last second, thrusting you into cool darkness.",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 110,
                            Content = "And then the air shifts and the darkness adjusts. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 111,
                            Content = "You’re outside, on a large lawn in the dead of night. The moon is high and bright, illuminating a large manor house. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 112,
                            Content = "Not an imitation of a manor house, not a show scene on a dark ride, you’re really there. The only thing connecting you back to your previous surroundings is the cart, but there is no track and you are completely still, facing the scene before you.",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 113,
                            Content = "The manor house isn’t especially large or imposing. The great expanse of the lawn is between you and the house, and the wind plays through it in a pleasant way as your eyes adjust to the moon-bright darkness. Trees are on either side of the house, and it is well-kept with three rows of plain windows catching a bit of the moonlight and reflecting it back towards you. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 114,
                            Content = "All in all, a pleasant, if confusing, place to be. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 115,
                            Content = "You notice the person crawling towards the manor house with a jolt. It seemed like there was no one there just moments ago, but now you see that a figure on all fours in a black robe-like garment is right before you. You are extremely grateful that the figure is moving away from you, for there is an extreme wrongness in the way it moves, a jittering, dragging sort of crawl that reminds you of glitched analog camera footage. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 116,
                            Content = "You close your eyes, perhaps willing yourself somewhere else, but you feel no change in the air. When you finally open your eyes again you are alone, but there is evidence for where your companion has gone: the first story window, to the left of the door, is open. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 117,
                            Content = "Oh, God, it’s gotten in. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 118,
                            Content = "And you are left waiting for what feels like hours. The safety bar on the cart is indeed clapped down fast and resists all attempts at escape you can muster. You must wait, staring into the darkness of the open window, wondering what the thing is doing inside. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 119,
                            Content = "Your attention drifts with time, and is only snapped back after the thing has exited the house again. It no longer crawls, and it moves quite swiftly, though its movements are still jittery and clumsy. The robe reaches only its knees where it falls into tatters. Long, confident strides on thin white legs brings it towards you. A hood obscures much of its emaciated face, but you can see enough. Oh, God, you can see enough. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 120,
                            Content = "And in its skinny arms, an unmoving baby. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 121,
                            Content = "Is it asleep?",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 122,
                            Content = "Is the baby asleep?",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 123,
                            Content = "You can't tell.",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 124,
                            Content = "You can’t tell at all, and even if you were brave enough (surely, you are brave enough) you cannot save this child, because you’re stuck in this damn cart. You cannot run to save yourself (surely, you would never do this) because you’re stuck in this damn cart. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 125,
                            Content = "But you do not need to worry, for you’re not actually in danger. The– person, figure, skeleton, corpse– the thing simply passes you by, confident in its purpose. It does not even turn its head to acknowledge you. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 126,
                            Content = "The baby does not move or make a sound.",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 127,
                            Content = "The wind blows hard, suddenly whipping the grass around and causing you to close your eyes against the granules blasted against your face. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 128,
                            Content = "Mechanical whirs and clinks and roars and your cart exits through a metal door painted to look as though it's made of wood. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 129,
                            Content = "The safety bar lifts easily once the cart comes to a stop. Gene is nowhere to be seen. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 130,
                            Content = "You stagger out of the cart on unsteady legs, feeling as though you just rode a modern high-speed roller coaster. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 131,
                            Content = "From behind you, you hear someone else stand up from the cart and walk onto the metal floor. In the corner of your eye, a black and white blurred figure steps beside you.",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 132,
                            Content = "You turn your head, and of course you are alone. ",
                            StoryId = "HauntedHouseYes"
                        },
                        new
                        {
                            Id = 133,
                            Content = "What a shame. It seemed like it would be fun.",
                            StoryId = "HauntedHouseNo"
                        },
                        new
                        {
                            Id = 134,
                            Content = "The Old Mill Ride has all the appearances of literally being in an old mill, a large wooden structure with a water wheel on the outside being pushed along by a not insignificant stream. There is an opening under the structure that lets the stream flow under and presumably through it. ",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 135,
                            Content = "There is none of the expected queue area that similar rides possess, just a yawning empty doorway to darkness. The only indication that this is indeed an attraction at a theme park is a very old paint job on the side of the building.",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 136,
                            Content = "“YE OLDE MILL” is painted in overwrought imitation medieval text across the aged wood.",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 137,
                            Content = "You enter through the wide doorway. It takes a moment for your eyes to adjust to the gloom inside, despite the rest of the park not being particularly bright. ",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 138,
                            Content = "The room is empty save for an extremely old man. He wears a faded polo shirt with a nametag that reads “Gene.” He looks tired, and greets you only with a slight wave of his hand. His sallow skin is the color of yellowed receipts. ",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 139,
                            Content = "He is standing by the stream, which is flanked on both sides by a poured concrete floor. A small boat waits by him, its movement down the stream hampered by a bar that must be manually lifted to let it continue into the depths of the ride. ",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 140,
                            Content = "“I miss my brother,” Gene confides to you as you approach, his voice bearing all the weight of his years. “I’m so confused now. Ray always knew what to do. I feel like I’m just going in circles.” He gestures to the boat and sighs. “Climb in.”",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 141,
                            Content = "Will you ride the Old Mill?",
                            StoryId = "OldMillMain"
                        },
                        new
                        {
                            Id = 142,
                            Content = "You must return here eventually, but perhaps now isn’t the time.",
                            StoryId = "OldMillNo"
                        },
                        new
                        {
                            Id = 143,
                            Content = "Gene somberly lifts the bar and your boat begins its journey down the stream. There is no safety bar on the boat, and the concrete floor is level with it. It would be very easy to stop the boat and get out at any time during this ride. ",
                            StoryId = "OldMillSaloon1"
                        },
                        new
                        {
                            Id = 144,
                            Content = "You pass through a short tunnel and are soon floating through an old west style saloon scene. A group of mannequins sit at a table playing a card game, one serving as bartender is busy pouring whiskey for a patron at the bar, and a particularly aged mannequin in a red dress stands atop a stage. A fuzzy recording of a woman singing “House of the Rising Sun” is playing over speakers you can’t see.",
                            StoryId = "OldMillSaloon1"
                        },
                        new
                        {
                            Id = 145,
                            Content = "Type “continue” to let your boat float on to the next scene, type “get out” to climb out of the boat and into the scene.",
                            StoryId = "OldMillSaloon1"
                        },
                        new
                        {
                            Id = 146,
                            Content = "You reach out to the concrete on either side to slow the boat, and easily clamber out. The boat continues down the stream without you. ",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 147,
                            Content = "The recording immediately sounds clearer now that you’re level with the scene. The performer is beginning the second verse, and the quality of her voice causes you to turn and look at the stage.",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 148,
                            Content = "A young woman in a red dress is standing there singing where the mannequin used to be. “If I had only listened to what my mama said, I’d be at home today. But bein’ so young and foolish, my Lord, let a gambler lead me astray.”",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 149,
                            Content = "“Hey!” The bartender calls to you. He’s finished pouring the drink and is passing it to the man in front of him. “Find a seat or buy a drink, but quit blockin’ the door!” ",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 150,
                            Content = "And you are blocking the door, aren’t you? You move to the bar past the card players. ",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 151,
                            Content = "The man who just received his drink is eyeing you. “You okay there, pardner? You look like you’ve seen a ghost.”",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 152,
                            Content = "You suppose the best thing to do is order a drink, and you do, before turning to the man who spoke and beginning to tell him all about the strange day you’ve been having. ",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 153,
                            Content = "END",
                            StoryId = "OldMillSaloon2"
                        },
                        new
                        {
                            Id = 154,
                            Content = "Continuing the old west theme, you find yourself looking at the inside of a jail cell. A mannequin dressed as a sheriff stands on the other side of the bars looking in at you and the single mannequin sitting on the dirt floor inside. ",
                            StoryId = "OldMillJail1"
                        },
                        new
                        {
                            Id = 155,
                            Content = "Type “continue” to let your boat float on to the next scene, type “get out” to climb out of the boat and into the scene.",
                            StoryId = "OldMillJail1"
                        },
                        new
                        {
                            Id = 156,
                            Content = "You reach out to the concrete on either side to slow the boat, and easily clamber out. The boat continues down the stream without you. ",
                            StoryId = "OldMillJail2"
                        },
                        new
                        {
                            Id = 157,
                            Content = "You immediately feel tired as you overlook the two mannequins. You decide to join the mannequin on the floor and sit down beside it. ",
                            StoryId = "OldMillJail2"
                        },
                        new
                        {
                            Id = 158,
                            Content = "Your limbs feel stiff, and stretching does not relieve this feeling. Your skin catches the light as you stretch. It’s shiny. In fact, it looks just like varnished wood. You rap your knuckles against the shiny spot on your skin, and it sounds just like two pieces of varnished wood being clunked together. ",
                            StoryId = "OldMillJail2"
                        },
                        new
                        {
                            Id = 159,
                            Content = "You don’t have much time to worry about this development, because the exhaustion is really taking hold now. You’re so tired your limbs are wooden, both literally and figuratively. A bit of a nap here couldn’t hurt.",
                            StoryId = "OldMillJail2"
                        },
                        new
                        {
                            Id = 160,
                            Content = "END",
                            StoryId = "OldMillJail2"
                        },
                        new
                        {
                            Id = 161,
                            Content = "The next scene is a graveyard complete with a skeleton in a cowboy hat propped up against the fence. A painted cardboard moon hangs high over the scene, and a painted backdrop shows a forest in the distance.",
                            StoryId = "OldMillGraveyard1"
                        },
                        new
                        {
                            Id = 162,
                            Content = "Type “Continue” to let your boat float on to the next scene, type “Get Out” to climb out of the boat and into the scene.",
                            StoryId = "OldMillGraveyard1"
                        },
                        new
                        {
                            Id = 163,
                            Content = "You reach out to the concrete on either side to slow the boat, and easily clamber out. The boat continues down the stream without you. ",
                            StoryId = "OldMillGraveyardDeerGodHelp"
                        },
                        new
                        {
                            Id = 164,
                            Content = "This scene is particularly poorly made. From the boat you could make out the corrugated sides of the gravestones, and here among the graves it’s even more obvious that they are just painted cardboard. ",
                            StoryId = "OldMillGraveyardDeerGodHelp"
                        },
                        new
                        {
                            Id = 165,
                            Content = "The forest backdrop is more intriguing, as it is painted skillfully by someone who really should be painting for somewhere other than Hill Cavern Fair. You can make out individual plants and trees, and– there is some animal in the forest, watching you. ",
                            StoryId = "OldMillGraveyardDeerGodHelp"
                        },
                        new
                        {
                            Id = 166,
                            Content = "You are drawn to that spot on the backdrop, heading forward to look closer. By the time you realize something is wrong, you’re already in the forest.",
                            StoryId = "OldMillGraveyardDeerGodHelp"
                        },
                        new
                        {
                            Id = 167,
                            Content = "A stag stands before you, twice your height and with twice as many legs as it should have. Its antlers are tall and many-branched, extending up into the trees where you are unable to see them end. Its eyes glow without any light source to reflect back.",
                            StoryId = "OldMillGraveyardDeerGodHelp"
                        },
                        new
                        {
                            Id = 168,
                            Content = "Its voice fills your mind.",
                            StoryId = "OldMillGraveyardDeerGodHelp"
                        },
                        new
                        {
                            Id = 169,
                            Content = "The Deer God kneels before you, its many jointed legs folding down unnaturally until it reaches a level where you could easily climb upon its back.",
                            StoryId = "OldMillGraveyardDeerGodHelpYes"
                        },
                        new
                        {
                            Id = 170,
                            Content = "You have no choice but to climb on. You do not expect it to actually take you home, but perhaps it will take you somewhere better than here.",
                            StoryId = "OldMillGraveyardDeerGodHelpYes"
                        },
                        new
                        {
                            Id = 171,
                            Content = "END",
                            StoryId = "OldMillGraveyardDeerGodHelpYes"
                        },
                        new
                        {
                            Id = 172,
                            Content = "I HAVE BEEN WAITING FOR YOU, SERVANT. FOLLOW ME.",
                            StoryId = "OldMillGraveyardDeerGodHelpNo"
                        },
                        new
                        {
                            Id = 173,
                            Content = "You have no choice but to follow the creature as it leads you deeper into the forest.",
                            StoryId = "OldMillGraveyardDeerGodHelpNo"
                        },
                        new
                        {
                            Id = 174,
                            Content = "END",
                            StoryId = "OldMillGraveyardDeerGodHelpNo"
                        },
                        new
                        {
                            Id = 175,
                            Content = "The boat reaches a dead end. There are no more scenes, only a black wall in front of you and a door to your right.",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 176,
                            Content = "You have no choice but to climb out and go through the door. ",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 177,
                            Content = "The sun shines brightly as you walk out onto the gravel. You’re at the entrance to Hill Cavern Fair, and a young man in a bright yellow polo shirt grins and waves at you. On his chest is a name tag that reads “Gene.”",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 178,
                            Content = "“Where’ve you been, Ray? I haven’t seen anyone yet!”",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 179,
                            Content = "You smile and pat your brother’s shoulder. “No need to be so anxious, Gene. It’s our first day. We’ve got lots of days ahead of us. If the tourists don’t come today, there’s tomorrow, and the day after that.”",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 180,
                            Content = "Gene nods, always attentive to your advice. “You’re right, of course, I just really want our opening day to be grand.”",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 181,
                            Content = "“It can be grand with just the two of us,” you promise, leading the way into your park.",
                            StoryId = "OldMillFinal"
                        },
                        new
                        {
                            Id = 182,
                            Content = "END",
                            StoryId = "OldMillFinal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
